version: '3'
services:
  osemosys:
    build: .
    image: yboulkaid/osemosys:latest
    environment:
      - 'RAILS_ENV=production'
      - 'RACK_ENV=production'
      - DATABASE_URL
      - RAILS_MASTER_KEY

    volumes:
      - .:/my_files
