version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: circleci/redis:3
    environment:
      - RACK_ENV: test

    steps:
      - checkout

      - run:
          name: install glpk
          command: |
            sudo apt-get update && sudo apt-get install glpk-utils coinor-cbc python3-pandas

      # Download and cache dependencies
      - restore_cache:
          keys:
          - osemosys-cloud-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - osemosys-cloud-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: install yarn dependencies
          command: |
            yarn install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: osemosys-cloud-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run:
          name: run tests
          command: |
            bundle exec rspec --format progress

  deploy_to_lighsail:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "bash -ic 'cd osemosys-cloud && ./scripts/deploy.sh'"

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy_to_lighsail:
          requires:
            - test
          filters:
            branches:
              only: master
