development:
  adapter: redis
  url: <%= OsemosysCloud::Redis.redis_url %>
  channel_prefix: osemosys-cloud_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= OsemosysCloud::Redis.redis_url %>
  channel_prefix: osemosys-cloud_production
