default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= "osemosys_cloud_#{Rails.env}" %>
  variables:
    statement_timeout: 10_000

development:
  <<: *default
  username: postgres
  host: localhost

test:
  <<: *default
  host: localhost
  username: <%= ENV.fetch('POSTGRES_USER', '') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>

production:
  <<: *default
  url: <%= Rails.application.credentials.dig(:postgres, :url) %>
