default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= "osemosys_cloud_#{Rails.env}" %>
  variables:
    statement_timeout: 10_000

development:
  <<: *default
  username: postgres
  host: localhost

test:
  <<: *default
  username: postgres
  host: localhost

production:
  <<: *default
  username: osemosys-cloud
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
