default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= "osemosys_cloud_#{Rails.env}" %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  username: postgres
  host: 127.0.0.1
  password: ''

test:
  <<: *default
  username: postgres
  host: 127.0.0.1
  password: ''

production:
  <<: *default
  username: tillin
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
